name: Weekly Challenge Management

on:
  # Run every Monday at 00:00 UTC
  schedule:
    - cron: '0 0 * * 1'
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (auto, create, list)'
        required: true
        default: 'auto'
        type: choice
        options:
          - auto
          - create
          - list

jobs:
  manage-challenges:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Supabase CLI
        uses: supabase/cli-action@v1
      
      - name: Call challenge management function
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          FUNCTION_SECRET: ${{ secrets.FUNCTION_SECRET }}
          SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
        run: |
          # Determine action based on trigger type
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            ACTION="${{ github.event.inputs.action }}"
          else
            ACTION="auto"
          fi
          
          # Call the Supabase Edge Function
          curl -i -X POST \
            "https://${SUPABASE_PROJECT_ID}.supabase.co/functions/v1/manage-challenges?action=${ACTION}" \
            -H "Authorization: Bearer ${FUNCTION_SECRET}" \
            -H "Content-Type: application/json"
      
      - name: Report result
        # Only run if the previous step succeeded
        if: success()
        run: echo "Challenge management completed successfully" 